#!/usr/bin/env bash
#Much much bad luck

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)	
			echo "bad lick from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((i++))
done
