#!/usr/bin/env bash
#A whole bunch of signals

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

while true; 
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate this kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid; exit' SIGQUIT
done
