#!/usr/bin/env bash
#A whole bunch of signals

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	trap 'echo "I hate this kill command"' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid' SIGQUIT
	trap 'rm /var/run/myscript.pid' SIGTERM
done
